[package]
name = "hello"
version = "0.1.0"
edition = "2018"

[dependencies]
aws_lambda_events = "0.3"
base64 = "0.12"
tokio = { version = "0.2", features = ["macros"] }
lambda = { git = "https://github.com/awslabs/aws-lambda-rust-runtime/", branch = "master"}
serde_json = "1.0"